# Generated by Django 4.1 on 2022-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_products_order_created_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_submitted_false",
        ),
        migrations.RemoveField(
            model_name="order",
            name="submitted",
        ),
        migrations.AddField(
            model_name="order",
            name="submitted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submitted_at", None)),
                fields=("submitted_at",),
                name="unique_submitted_at_None",
            ),
        ),
    ]
