# Generated by Django 4.1 on 2022-11-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("quantity_in_stock", models.PositiveIntegerField()),
            ],
        ),
    ]
